Added technical documentation
SpeciesConservationLandscapes/task_hii_power pull request #7
Opened 2021-11-18 15:37 UTC by thanrobinson

2021-11-18 15:38 UTC, thanrobinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [HII Power Read Me](https://trello.com/c/XaWlJwKt/347-hii-power-read-me)

2021-12-03 00:01 UTC, saanobhaai requested changes
Just some typos and suggested rewording

2021-12-03 00:01 UTC, saanobhaai commented on README.md
> +This task calculates the (unitless) "influence" of power on the terrestrial surface as one of the key drivers for a combined [Human Influence Index](https://github.com/SpeciesConservationLandscapes/t
- calculated from
- is transformed -- should do a global search for remaining past/passive verbs

2021-12-03 00:01 UTC, saanobhaai commented on README.md
> +### Input Dataset Callibration
Calibration (single l; do a global search/replace)

2021-12-03 00:01 UTC, saanobhaai commented on README.md
> +Two distinct nightlight datasets are integrated to produce an annually calibrated dataset of nightlights from 1992 through the present. These the [Defense Meteorological Satellite Program (DMSP)/Oper
The HII power driver (0-10) is calculated from the previous calendar year's calibrated nightlights dataset, which is produced on demand by the task. Two distinct source nightlight datasets are used to calculate this calibrated version following the methods below; these are the [Defense Meteorological Satellite Program (DMSP)/Operational Linescan System (OLS)](https://eogdata.mines.edu/products/dmsp/) and the [Visible Infrared Imaging Radiometry Suite (VIIRS) on the Suomi National Polar-orbiting Partnership Satellite](https://eogdata.mines.edu/products/vnl/). DMSP provides data from 1992 - 2013 and VIIRS provides data from 2012 through the present.

2021-12-03 00:01 UTC, saanobhaai commented on README.md
> +Inconsistencies within the DMSP time series requires implementing intra-calibration within the DMPS dataset. Here the intra-calibrated dataset produced by [Li et al. 2020](https://www.nature.com/arti
require

2021-12-03 00:01 UTC, saanobhaai commented on README.md
> +3. Regression coeffecients were calculated to convert VIIRS values to DMPS values by comparing pixel values of areas with stable lights through time. These were determined by selecting pixels from th
DMSP

2021-12-06 14:57 UTC, merged